name: Nasa project CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  builds:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ["4.2", "4.4"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Use mongodb for github actions
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}

      - name: Install dependencies
        run: npm install

      - name: Build client
        run: npm run build --prefix client
      - run: npm test
